[versions]
agp = "8.3.2"
compose-compiler = "1.5.11"
kotlin = "1.9.23"
ktlint = "0.48.1"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidActivityCompose = "androidx.activity:activity-compose:1.8.2"
androidAnnotation = "androidx.annotation:annotation:1.7.1"
androidCollection = "androidx.collection:collection:1.4.0"
androidTestRunner = "androidx.test:runner:1.5.2"
composeCompiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
composeMaterial = "androidx.compose.material:material:1.6.5"
composeUi = "androidx.compose.ui:ui:1.6.5"
googleMaterial = "com.google.android.material:material:1.11.0"
icu4j = "com.ibm.icu:icu4j:75.1"
junit = "junit:junit:4.13.2"
kotlinPoet = "com.squareup:kotlinpoet:1.16.0"
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector:1.15"
truth = "com.google.truth:truth:1.4.2"
coreLibraryDesugaring = "com.android.tools:desugar_jdk_libs:2.0.4"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.3.5" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.28.0" }
poko = { id = "dev.drewhamilton.poko", version = "0.15.2" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
kotlinApiDump = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.14.0" }
