[versions]
agp = "9.0.0-beta02"
kotlin = "2.2.21"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidActivityCompose = "androidx.activity:activity-compose:1.12.0"
androidAnnotation = "androidx.annotation:annotation:1.9.1"
androidCollection = "androidx.collection:collection:1.5.0"
androidTestRunner = "androidx.test:runner:1.7.0"
composeMaterial = "androidx.compose.material:material:1.9.5"
composeUi = "androidx.compose.ui:ui:1.9.5"
googleMaterial = "com.google.android.material:material:1.13.0"
icu4j = "com.ibm.icu:icu4j:78.1"
junit = "junit:junit:4.13.2"
kotlinPoet = "com.squareup:kotlinpoet:2.2.0"
robolectric = "org.robolectric:robolectric:4.16"
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector:1.20"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
coreLibraryDesugaring = "com.android.tools:desugar_jdk_libs:2.1.5"
ktfmt = "com.facebook:ktfmt:0.59"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.1" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
poko = { id = "dev.drewhamilton.poko", version = "0.20.2" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
kotlinApiDump = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
