[versions]
agp = "7.4.1"
kotlin = "1.7.10"
ktlint = "0.48.1"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidActivityCompose = "androidx.activity:activity-compose:1.5.1"
androidAnnotation = "androidx.annotation:annotation:1.5.0"
androidTestRunner = "androidx.test:runner:1.5.2"
composeMaterial = "androidx.compose.material:material:1.3.1"
composeUi = "androidx.compose.ui:ui:1.3.1"
googleMaterial = "com.google.android.material:material:1.8.0"
icu4j = "com.ibm.icu:icu4j:72.1"
junit = "junit:junit:4.13.2"
kotlinPoet = "com.squareup:kotlinpoet:1.12.0"
truth = "com.google.truth:truth:1.1.3"
coreLibraryDesugaring = "com.android.tools:desugar_jdk_libs:1.2.2"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "3.1.0" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.24.0" }
spotless = { id = "com.diffplug.spotless", version = "6.13.0" }
