[versions]
agp = "7.4.2"
compose-compiler = "1.4.4"
kotlin = "1.8.10"
ktlint = "0.48.1"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidActivityCompose = "androidx.activity:activity-compose:1.7.0"
androidAnnotation = "androidx.annotation:annotation:1.6.0"
androidCollection = "androidx.collection:collection:1.2.0"
androidTestRunner = "androidx.test:runner:1.5.2"
composeCompiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
composeMaterial = "androidx.compose.material:material:1.4.1"
composeUi = "androidx.compose.ui:ui:1.4.1"
googleMaterial = "com.google.android.material:material:1.8.0"
icu4j = "com.ibm.icu:icu4j:72.1"
junit = "junit:junit:4.13.2"
kotlinPoet = "com.squareup:kotlinpoet:1.13.0"
testParameterInjector = "com.google.testparameterinjector:test-parameter-injector:1.11"
truth = "com.google.truth:truth:1.1.3"
coreLibraryDesugaring = "com.android.tools:desugar_jdk_libs:2.0.3"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "3.1.0" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.10" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.25.1" }
spotless = { id = "com.diffplug.spotless", version = "6.18.0" }
